#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_Thu_Vien")]
	public partial class QL_Thu_VienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_tacgia(tbl_tacgia instance);
    partial void Updatetbl_tacgia(tbl_tacgia instance);
    partial void Deletetbl_tacgia(tbl_tacgia instance);
    partial void Inserttbl_docgia(tbl_docgia instance);
    partial void Updatetbl_docgia(tbl_docgia instance);
    partial void Deletetbl_docgia(tbl_docgia instance);
    partial void Inserttbl_linhvuc(tbl_linhvuc instance);
    partial void Updatetbl_linhvuc(tbl_linhvuc instance);
    partial void Deletetbl_linhvuc(tbl_linhvuc instance);
    partial void Inserttbl_nhanvien(tbl_nhanvien instance);
    partial void Updatetbl_nhanvien(tbl_nhanvien instance);
    partial void Deletetbl_nhanvien(tbl_nhanvien instance);
    partial void Inserttbl_nxb(tbl_nxb instance);
    partial void Updatetbl_nxb(tbl_nxb instance);
    partial void Deletetbl_nxb(tbl_nxb instance);
    partial void Inserttbl_phieumuon_tra(tbl_phieumuon_tra instance);
    partial void Updatetbl_phieumuon_tra(tbl_phieumuon_tra instance);
    partial void Deletetbl_phieumuon_tra(tbl_phieumuon_tra instance);
    partial void Inserttbl_sach(tbl_sach instance);
    partial void Updatetbl_sach(tbl_sach instance);
    partial void Deletetbl_sach(tbl_sach instance);
    #endregion
		
		public QL_Thu_VienDataContext() : 
				base(global::DoAnCNPM.Properties.Settings.Default.QL_Thu_VienConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QL_Thu_VienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_Thu_VienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_Thu_VienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_Thu_VienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_tacgia> tbl_tacgias
		{
			get
			{
				return this.GetTable<tbl_tacgia>();
			}
		}
		
		public System.Data.Linq.Table<tbl_docgia> tbl_docgias
		{
			get
			{
				return this.GetTable<tbl_docgia>();
			}
		}
		
		public System.Data.Linq.Table<tbl_linhvuc> tbl_linhvucs
		{
			get
			{
				return this.GetTable<tbl_linhvuc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_nhanvien> tbl_nhanviens
		{
			get
			{
				return this.GetTable<tbl_nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_nxb> tbl_nxbs
		{
			get
			{
				return this.GetTable<tbl_nxb>();
			}
		}
		
		public System.Data.Linq.Table<tbl_phieumuon_tra> tbl_phieumuon_tras
		{
			get
			{
				return this.GetTable<tbl_phieumuon_tra>();
			}
		}
		
		public System.Data.Linq.Table<tbl_sach> tbl_saches
		{
			get
			{
				return this.GetTable<tbl_sach>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tacgia")]
	public partial class tbl_tacgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _matg;
		
		private string _tentg;
		
		private string _gioitinh;
		
		private string _diachi;
		
		private EntitySet<tbl_sach> _tbl_saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatgChanging(int value);
    partial void OnmatgChanged();
    partial void OntentgChanging(string value);
    partial void OntentgChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public tbl_tacgia()
		{
			this._tbl_saches = new EntitySet<tbl_sach>(new Action<tbl_sach>(this.attach_tbl_saches), new Action<tbl_sach>(this.detach_tbl_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matg", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int matg
		{
			get
			{
				return this._matg;
			}
			set
			{
				if ((this._matg != value))
				{
					this.OnmatgChanging(value);
					this.SendPropertyChanging();
					this._matg = value;
					this.SendPropertyChanged("matg");
					this.OnmatgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentg", DbType="NVarChar(50)")]
		public string tentg
		{
			get
			{
				return this._tentg;
			}
			set
			{
				if ((this._tentg != value))
				{
					this.OntentgChanging(value);
					this.SendPropertyChanging();
					this._tentg = value;
					this.SendPropertyChanged("tentg");
					this.OntentgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(3)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tacgia_tbl_sach", Storage="_tbl_saches", ThisKey="matg", OtherKey="matg")]
		public EntitySet<tbl_sach> tbl_saches
		{
			get
			{
				return this._tbl_saches;
			}
			set
			{
				this._tbl_saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tacgia = this;
		}
		
		private void detach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tacgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_docgia")]
	public partial class tbl_docgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _madg;
		
		private string _tendg;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _lop;
		
		private string _diachi;
		
		private string _email;
		
		private EntitySet<tbl_phieumuon_tra> _tbl_phieumuon_tras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadgChanging(int value);
    partial void OnmadgChanged();
    partial void OntendgChanging(string value);
    partial void OntendgChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnlopChanging(string value);
    partial void OnlopChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public tbl_docgia()
		{
			this._tbl_phieumuon_tras = new EntitySet<tbl_phieumuon_tra>(new Action<tbl_phieumuon_tra>(this.attach_tbl_phieumuon_tras), new Action<tbl_phieumuon_tra>(this.detach_tbl_phieumuon_tras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madg", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int madg
		{
			get
			{
				return this._madg;
			}
			set
			{
				if ((this._madg != value))
				{
					this.OnmadgChanging(value);
					this.SendPropertyChanging();
					this._madg = value;
					this.SendPropertyChanged("madg");
					this.OnmadgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendg", DbType="NVarChar(50)")]
		public string tendg
		{
			get
			{
				return this._tendg;
			}
			set
			{
				if ((this._tendg != value))
				{
					this.OntendgChanging(value);
					this.SendPropertyChanging();
					this._tendg = value;
					this.SendPropertyChanged("tendg");
					this.OntendgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(3)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lop", DbType="VarChar(10)")]
		public string lop
		{
			get
			{
				return this._lop;
			}
			set
			{
				if ((this._lop != value))
				{
					this.OnlopChanging(value);
					this.SendPropertyChanging();
					this._lop = value;
					this.SendPropertyChanged("lop");
					this.OnlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_docgia_tbl_phieumuon_tra", Storage="_tbl_phieumuon_tras", ThisKey="madg", OtherKey="madg")]
		public EntitySet<tbl_phieumuon_tra> tbl_phieumuon_tras
		{
			get
			{
				return this._tbl_phieumuon_tras;
			}
			set
			{
				this._tbl_phieumuon_tras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_phieumuon_tras(tbl_phieumuon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_docgia = this;
		}
		
		private void detach_tbl_phieumuon_tras(tbl_phieumuon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_docgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_linhvuc")]
	public partial class tbl_linhvuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _malinhvuc;
		
		private string _tenlinhvuc;
		
		private EntitySet<tbl_sach> _tbl_saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmalinhvucChanging(int value);
    partial void OnmalinhvucChanged();
    partial void OntenlinhvucChanging(string value);
    partial void OntenlinhvucChanged();
    #endregion
		
		public tbl_linhvuc()
		{
			this._tbl_saches = new EntitySet<tbl_sach>(new Action<tbl_sach>(this.attach_tbl_saches), new Action<tbl_sach>(this.detach_tbl_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malinhvuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int malinhvuc
		{
			get
			{
				return this._malinhvuc;
			}
			set
			{
				if ((this._malinhvuc != value))
				{
					this.OnmalinhvucChanging(value);
					this.SendPropertyChanging();
					this._malinhvuc = value;
					this.SendPropertyChanged("malinhvuc");
					this.OnmalinhvucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlinhvuc", DbType="NVarChar(100)")]
		public string tenlinhvuc
		{
			get
			{
				return this._tenlinhvuc;
			}
			set
			{
				if ((this._tenlinhvuc != value))
				{
					this.OntenlinhvucChanging(value);
					this.SendPropertyChanging();
					this._tenlinhvuc = value;
					this.SendPropertyChanged("tenlinhvuc");
					this.OntenlinhvucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_linhvuc_tbl_sach", Storage="_tbl_saches", ThisKey="malinhvuc", OtherKey="malv")]
		public EntitySet<tbl_sach> tbl_saches
		{
			get
			{
				return this._tbl_saches;
			}
			set
			{
				this._tbl_saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_linhvuc = this;
		}
		
		private void detach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_linhvuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_nhanvien")]
	public partial class tbl_nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _manv;
		
		private string _tennv;
		
		private string _diachi;
		
		private string _dienthoai;
		
		private string _email;
		
		private string _chucvu;
		
		private System.Nullable<int> _tuoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(int value);
    partial void OnmanvChanged();
    partial void OntennvChanging(string value);
    partial void OntennvChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnchucvuChanging(string value);
    partial void OnchucvuChanged();
    partial void OntuoiChanging(System.Nullable<int> value);
    partial void OntuoiChanged();
    #endregion
		
		public tbl_nhanvien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennv", DbType="NVarChar(50)")]
		public string tennv
		{
			get
			{
				return this._tennv;
			}
			set
			{
				if ((this._tennv != value))
				{
					this.OntennvChanging(value);
					this.SendPropertyChanging();
					this._tennv = value;
					this.SendPropertyChanged("tennv");
					this.OntennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="VarChar(11)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucvu", DbType="NVarChar(100)")]
		public string chucvu
		{
			get
			{
				return this._chucvu;
			}
			set
			{
				if ((this._chucvu != value))
				{
					this.OnchucvuChanging(value);
					this.SendPropertyChanging();
					this._chucvu = value;
					this.SendPropertyChanged("chucvu");
					this.OnchucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuoi", DbType="Int")]
		public System.Nullable<int> tuoi
		{
			get
			{
				return this._tuoi;
			}
			set
			{
				if ((this._tuoi != value))
				{
					this.OntuoiChanging(value);
					this.SendPropertyChanging();
					this._tuoi = value;
					this.SendPropertyChanged("tuoi");
					this.OntuoiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_nxb")]
	public partial class tbl_nxb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _manxb;
		
		private string _tennxb;
		
		private string _diachi;
		
		private string _sdt;
		
		private EntitySet<tbl_sach> _tbl_saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanxbChanging(int value);
    partial void OnmanxbChanged();
    partial void OntennxbChanging(string value);
    partial void OntennxbChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    #endregion
		
		public tbl_nxb()
		{
			this._tbl_saches = new EntitySet<tbl_sach>(new Action<tbl_sach>(this.attach_tbl_saches), new Action<tbl_sach>(this.detach_tbl_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manxb", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int manxb
		{
			get
			{
				return this._manxb;
			}
			set
			{
				if ((this._manxb != value))
				{
					this.OnmanxbChanging(value);
					this.SendPropertyChanging();
					this._manxb = value;
					this.SendPropertyChanged("manxb");
					this.OnmanxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennxb", DbType="VarChar(100)")]
		public string tennxb
		{
			get
			{
				return this._tennxb;
			}
			set
			{
				if ((this._tennxb != value))
				{
					this.OntennxbChanging(value);
					this.SendPropertyChanging();
					this._tennxb = value;
					this.SendPropertyChanged("tennxb");
					this.OntennxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(200)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(11)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_nxb_tbl_sach", Storage="_tbl_saches", ThisKey="manxb", OtherKey="manxb")]
		public EntitySet<tbl_sach> tbl_saches
		{
			get
			{
				return this._tbl_saches;
			}
			set
			{
				this._tbl_saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_nxb = this;
		}
		
		private void detach_tbl_saches(tbl_sach entity)
		{
			this.SendPropertyChanging();
			entity.tbl_nxb = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_phieumuon_tra")]
	public partial class tbl_phieumuon_tra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sophieumuon;
		
		private System.Nullable<int> _madg;
		
		private System.Nullable<int> _masach;
		
		private System.Nullable<System.DateTime> _ngaymuon;
		
		private System.Nullable<System.DateTime> _ngaytra;
		
		private System.Nullable<bool> _xacnhantra;
		
		private string _ghichu;
		
		private EntityRef<tbl_docgia> _tbl_docgia;
		
		private EntityRef<tbl_sach> _tbl_sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsophieumuonChanging(int value);
    partial void OnsophieumuonChanged();
    partial void OnmadgChanging(System.Nullable<int> value);
    partial void OnmadgChanged();
    partial void OnmasachChanging(System.Nullable<int> value);
    partial void OnmasachChanged();
    partial void OnngaymuonChanging(System.Nullable<System.DateTime> value);
    partial void OnngaymuonChanged();
    partial void OnngaytraChanging(System.Nullable<System.DateTime> value);
    partial void OnngaytraChanged();
    partial void OnxacnhantraChanging(System.Nullable<bool> value);
    partial void OnxacnhantraChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public tbl_phieumuon_tra()
		{
			this._tbl_docgia = default(EntityRef<tbl_docgia>);
			this._tbl_sach = default(EntityRef<tbl_sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sophieumuon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sophieumuon
		{
			get
			{
				return this._sophieumuon;
			}
			set
			{
				if ((this._sophieumuon != value))
				{
					this.OnsophieumuonChanging(value);
					this.SendPropertyChanging();
					this._sophieumuon = value;
					this.SendPropertyChanged("sophieumuon");
					this.OnsophieumuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madg", DbType="Int")]
		public System.Nullable<int> madg
		{
			get
			{
				return this._madg;
			}
			set
			{
				if ((this._madg != value))
				{
					if (this._tbl_docgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadgChanging(value);
					this.SendPropertyChanging();
					this._madg = value;
					this.SendPropertyChanged("madg");
					this.OnmadgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masach", DbType="Int")]
		public System.Nullable<int> masach
		{
			get
			{
				return this._masach;
			}
			set
			{
				if ((this._masach != value))
				{
					if (this._tbl_sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmasachChanging(value);
					this.SendPropertyChanging();
					this._masach = value;
					this.SendPropertyChanged("masach");
					this.OnmasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaymuon", DbType="Date")]
		public System.Nullable<System.DateTime> ngaymuon
		{
			get
			{
				return this._ngaymuon;
			}
			set
			{
				if ((this._ngaymuon != value))
				{
					this.OnngaymuonChanging(value);
					this.SendPropertyChanging();
					this._ngaymuon = value;
					this.SendPropertyChanged("ngaymuon");
					this.OnngaymuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytra", DbType="Date")]
		public System.Nullable<System.DateTime> ngaytra
		{
			get
			{
				return this._ngaytra;
			}
			set
			{
				if ((this._ngaytra != value))
				{
					this.OnngaytraChanging(value);
					this.SendPropertyChanging();
					this._ngaytra = value;
					this.SendPropertyChanged("ngaytra");
					this.OnngaytraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xacnhantra", DbType="Bit")]
		public System.Nullable<bool> xacnhantra
		{
			get
			{
				return this._xacnhantra;
			}
			set
			{
				if ((this._xacnhantra != value))
				{
					this.OnxacnhantraChanging(value);
					this.SendPropertyChanging();
					this._xacnhantra = value;
					this.SendPropertyChanged("xacnhantra");
					this.OnxacnhantraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(300)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_docgia_tbl_phieumuon_tra", Storage="_tbl_docgia", ThisKey="madg", OtherKey="madg", IsForeignKey=true)]
		public tbl_docgia tbl_docgia
		{
			get
			{
				return this._tbl_docgia.Entity;
			}
			set
			{
				tbl_docgia previousValue = this._tbl_docgia.Entity;
				if (((previousValue != value) 
							|| (this._tbl_docgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_docgia.Entity = null;
						previousValue.tbl_phieumuon_tras.Remove(this);
					}
					this._tbl_docgia.Entity = value;
					if ((value != null))
					{
						value.tbl_phieumuon_tras.Add(this);
						this._madg = value.madg;
					}
					else
					{
						this._madg = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_docgia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_sach_tbl_phieumuon_tra", Storage="_tbl_sach", ThisKey="masach", OtherKey="masach", IsForeignKey=true)]
		public tbl_sach tbl_sach
		{
			get
			{
				return this._tbl_sach.Entity;
			}
			set
			{
				tbl_sach previousValue = this._tbl_sach.Entity;
				if (((previousValue != value) 
							|| (this._tbl_sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_sach.Entity = null;
						previousValue.tbl_phieumuon_tras.Remove(this);
					}
					this._tbl_sach.Entity = value;
					if ((value != null))
					{
						value.tbl_phieumuon_tras.Add(this);
						this._masach = value.masach;
					}
					else
					{
						this._masach = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sach")]
	public partial class tbl_sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _masach;
		
		private string _tensach;
		
		private System.Nullable<int> _matg;
		
		private System.Nullable<int> _manxb;
		
		private System.Nullable<int> _malv;
		
		private System.Nullable<int> _sotrang;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<System.DateTime> _ngaynhap;
		
		private EntitySet<tbl_phieumuon_tra> _tbl_phieumuon_tras;
		
		private EntityRef<tbl_linhvuc> _tbl_linhvuc;
		
		private EntityRef<tbl_nxb> _tbl_nxb;
		
		private EntityRef<tbl_tacgia> _tbl_tacgia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasachChanging(int value);
    partial void OnmasachChanged();
    partial void OntensachChanging(string value);
    partial void OntensachChanged();
    partial void OnmatgChanging(System.Nullable<int> value);
    partial void OnmatgChanged();
    partial void OnmanxbChanging(System.Nullable<int> value);
    partial void OnmanxbChanged();
    partial void OnmalvChanging(System.Nullable<int> value);
    partial void OnmalvChanged();
    partial void OnsotrangChanging(System.Nullable<int> value);
    partial void OnsotrangChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaynhapChanged();
    #endregion
		
		public tbl_sach()
		{
			this._tbl_phieumuon_tras = new EntitySet<tbl_phieumuon_tra>(new Action<tbl_phieumuon_tra>(this.attach_tbl_phieumuon_tras), new Action<tbl_phieumuon_tra>(this.detach_tbl_phieumuon_tras));
			this._tbl_linhvuc = default(EntityRef<tbl_linhvuc>);
			this._tbl_nxb = default(EntityRef<tbl_nxb>);
			this._tbl_tacgia = default(EntityRef<tbl_tacgia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int masach
		{
			get
			{
				return this._masach;
			}
			set
			{
				if ((this._masach != value))
				{
					this.OnmasachChanging(value);
					this.SendPropertyChanging();
					this._masach = value;
					this.SendPropertyChanged("masach");
					this.OnmasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensach", DbType="NVarChar(100)")]
		public string tensach
		{
			get
			{
				return this._tensach;
			}
			set
			{
				if ((this._tensach != value))
				{
					this.OntensachChanging(value);
					this.SendPropertyChanging();
					this._tensach = value;
					this.SendPropertyChanged("tensach");
					this.OntensachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matg", DbType="Int")]
		public System.Nullable<int> matg
		{
			get
			{
				return this._matg;
			}
			set
			{
				if ((this._matg != value))
				{
					if (this._tbl_tacgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatgChanging(value);
					this.SendPropertyChanging();
					this._matg = value;
					this.SendPropertyChanged("matg");
					this.OnmatgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manxb", DbType="Int")]
		public System.Nullable<int> manxb
		{
			get
			{
				return this._manxb;
			}
			set
			{
				if ((this._manxb != value))
				{
					if (this._tbl_nxb.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanxbChanging(value);
					this.SendPropertyChanging();
					this._manxb = value;
					this.SendPropertyChanged("manxb");
					this.OnmanxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malv", DbType="Int")]
		public System.Nullable<int> malv
		{
			get
			{
				return this._malv;
			}
			set
			{
				if ((this._malv != value))
				{
					if (this._tbl_linhvuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmalvChanging(value);
					this.SendPropertyChanging();
					this._malv = value;
					this.SendPropertyChanged("malv");
					this.OnmalvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotrang", DbType="Int")]
		public System.Nullable<int> sotrang
		{
			get
			{
				return this._sotrang;
			}
			set
			{
				if ((this._sotrang != value))
				{
					this.OnsotrangChanging(value);
					this.SendPropertyChanging();
					this._sotrang = value;
					this.SendPropertyChanged("sotrang");
					this.OnsotrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_sach_tbl_phieumuon_tra", Storage="_tbl_phieumuon_tras", ThisKey="masach", OtherKey="masach")]
		public EntitySet<tbl_phieumuon_tra> tbl_phieumuon_tras
		{
			get
			{
				return this._tbl_phieumuon_tras;
			}
			set
			{
				this._tbl_phieumuon_tras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_linhvuc_tbl_sach", Storage="_tbl_linhvuc", ThisKey="malv", OtherKey="malinhvuc", IsForeignKey=true)]
		public tbl_linhvuc tbl_linhvuc
		{
			get
			{
				return this._tbl_linhvuc.Entity;
			}
			set
			{
				tbl_linhvuc previousValue = this._tbl_linhvuc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_linhvuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_linhvuc.Entity = null;
						previousValue.tbl_saches.Remove(this);
					}
					this._tbl_linhvuc.Entity = value;
					if ((value != null))
					{
						value.tbl_saches.Add(this);
						this._malv = value.malinhvuc;
					}
					else
					{
						this._malv = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_linhvuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_nxb_tbl_sach", Storage="_tbl_nxb", ThisKey="manxb", OtherKey="manxb", IsForeignKey=true)]
		public tbl_nxb tbl_nxb
		{
			get
			{
				return this._tbl_nxb.Entity;
			}
			set
			{
				tbl_nxb previousValue = this._tbl_nxb.Entity;
				if (((previousValue != value) 
							|| (this._tbl_nxb.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_nxb.Entity = null;
						previousValue.tbl_saches.Remove(this);
					}
					this._tbl_nxb.Entity = value;
					if ((value != null))
					{
						value.tbl_saches.Add(this);
						this._manxb = value.manxb;
					}
					else
					{
						this._manxb = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_nxb");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tacgia_tbl_sach", Storage="_tbl_tacgia", ThisKey="matg", OtherKey="matg", IsForeignKey=true)]
		public tbl_tacgia tbl_tacgia
		{
			get
			{
				return this._tbl_tacgia.Entity;
			}
			set
			{
				tbl_tacgia previousValue = this._tbl_tacgia.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tacgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tacgia.Entity = null;
						previousValue.tbl_saches.Remove(this);
					}
					this._tbl_tacgia.Entity = value;
					if ((value != null))
					{
						value.tbl_saches.Add(this);
						this._matg = value.matg;
					}
					else
					{
						this._matg = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_tacgia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_phieumuon_tras(tbl_phieumuon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_sach = this;
		}
		
		private void detach_tbl_phieumuon_tras(tbl_phieumuon_tra entity)
		{
			this.SendPropertyChanging();
			entity.tbl_sach = null;
		}
	}
}
#pragma warning restore 1591
